### ISSUE TITLE
block_device_mappings should support default values

### ISSUE THREAD

**Issue by l15k4** [petrjanda/coreos-ec2#3]
In order to declare just bare minimum volume configuration : 

``` yaml
volumes:
  -
    name: /dev/xvda
    size: 20
```

leaving the other properties to default, the implementation must change because it forces you to declare everything : 

``` python
    @property
    def block_device_mappings(self):
        """ Block device mapping for EC2 instance creation """

        return [dict(
            DeviceName=v['name'],
            Ebs=dict(
                VolumeSize=v['size'],
                VolumeType=v['volume_type'],
                DeleteOnTermination=v['delete_on_termination']
            )
        ) for v in self._volumes]
```

**Comment by petrjanda** [comment]
Makes sense, would we just provide defaults in the code and override it by the configuration spec? Sort of recursive merge of `default` and `config`?

**Comment by l15k4** [comment]
No I meant that if you pass just `dict` with  `DeviceName` and `Ebs=dict(VolumeSize=v['size'])` only, it will work ... all the params are optionall in boto3 and aws-client ... when describing a block device mapping in aws-cli you just need to specify a name and `Ebs` or `VirtualName`, `type` and `delete_on_termination` have defaults... 

for EBS:

```
aws ec2 run-instances --image-id ami-xxxxxxxx --instance-type m1.xlarge --block-device-mappings '{"DeviceName": "/dev/xvda1","Ebs" : { "VolumeSize" : 50 }}'
```

or for instance store : 

```
aws ec2 run-instances --image-id ami-xxxxxxxx --instance-type m1.xlarge --block-device-mappings '{"DeviceName": "/dev/xvda1","VirtualName": "ephemeral0"}'
```

**Comment by petrjanda** [comment]
Right, I was revising thinking that way as well. There is a cool trick we can do I believe.

**Comment by l15k4** [comment]
I guess that since c3.large has 2 x `16 GB SSD (32 GB)` disks, you could define 2 block device mappings like : 

```
'{"DeviceName": "/dev/xvda1","VirtualName": "ephemeral0"}'
'{"DeviceName": "/dev/xvdb1","VirtualName": "ephemeral1"}'
```

**Comment by l15k4** [comment]
Btw there are 2 kinds of AMIs:

**Comment by l15k4** [comment]
Btw there are 2 kinds of AMIs : 
1) an instance store-backed AMI 
2) an Amazon EBS-backed AMI

So in order to have a root volume either "instance store based" or "EBS based" you need to pick the right AMI.

There is a fact to consider, you are paying for the instance stores even though you are not using them, so it would be wise to utilize them.
